local s,id=GetID()
function s.initial_effect(c)
	Kirafan3.SpCreamateSgHeal(c,4)
	Kirafan3.SpCreamateAllHeal(c,2)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(10050113,4))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(Kirafan6.spcreamatecon)
	e1:SetCost(Kirafan2.spdottecost(1,5))
	e1:SetTarget(Kirafan6.nodamtg)
	e1:SetOperation(s.dotteop)
	c:RegisterEffect(e1)
	Kirafan3.SpCreamateCharacter(c)
end
function s.dotteop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local con=Duel.GetMatchingGroupCount(Kirafan6.NoEmFzonefilter,tp,0,LOCATION_MZONE,nil)
	if con>2 then
	Kirafan6.kirafandrawop(e,tp,eg,ep,ev,re,r,rp,3)
	Duel.Hint(HINT_SELECTMSG,tp,aux.Stringid(10050111,10))
	local g=Duel.SelectMatchingCard(tp,nil,tp,LOCATION_HAND,0,1,1,nil)
	local tg=g:GetFirst()
	Duel.SendtoGrave(tg,REASON_RULE)
	elseif con==2 then Kirafan6.kirafandrawop(e,tp,eg,ep,ev,re,r,rp,2)
	else Kirafan6.kirafandrawop(e,tp,eg,ep,ev,re,r,rp,1) end
end