local s,id=GetID()
function s.initial_effect(c)
	Kirafan3.SpCreamateSgHeal(c,4)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(10050113,4))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(Kirafan6.spcreamatecon)
	e1:SetCost(Kirafan2.spdotterestcost(2,1,5))
	e1:SetTarget(Kirafan6.nospdamtg)
	e1:SetOperation(s.dotteop)
	c:RegisterEffect(e1)
	Kirafan3.SpCreamateCharacter(c)
end
function s.dotteop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local main=Duel.GetMatchingGroup(nil,tp,LOCATION_EMZONE,0,nil):GetFirst()
	local g=Duel.GetMatchingGroup(Kirafan6.NoEmFzonefilter,tp,LOCATION_MZONE,0,nil)
	main:AddCounter(0xc03,1)
	local atk=math.min(main:GetCounter(0xc03),3)
	Kirafan6.nextatkchange(e,tp,eg,ep,ev,re,r,rp,g,atk)
end