local s,id=GetID()
function s.initial_effect(c)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(Kirafan6.spcreamatecon)
	e1:SetCost(Kirafan2.spcost(3))
	e1:SetTarget(Kirafan6.spdamtg)
	e1:SetOperation(s.op)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetType(EFFECT_TYPE_QUICK_O)
	e2:SetCode(EVENT_FREE_CHAIN)
	e2:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e2:SetRange(LOCATION_HAND)
	e2:SetCondition(Kirafan6.spcreamatecon)
	e2:SetCost(Kirafan2.spcost(4)) 
	e2:SetTarget(Kirafan6.spdamtg)
	e2:SetOperation(s.op2)
	c:RegisterEffect(e2)	
	Kirafan3.SpCreamateCharacter(c)
end
function s.op(e,tp,eg,ep,ev,re,r,rp)
	local tc=Duel.GetFirstTarget()
	Kirafan6.statuseff(e,tp,eg,ep,ev,re,r,rp,tc,0xc02,3)
end
function s.op2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	Kirafan6.statusreset(e,tp,eg,ep,ev,re,r,rp,tc)
	Kirafan6.drawtrigger(c)
end