local s,id=GetID()
function s.initial_effect(c)
	Kirafan3.SpCreamateOvSgHeal(c,3)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(Kirafan6.spcreamatecon)
	e1:SetCost(Kirafan2.spcost(3))
	e1:SetTarget(Kirafan6.nospcondamtg)
	e1:SetOperation(s.op1)
	c:RegisterEffect(e1)
	local e2=Effect.CreateEffect(c)
	e2:SetDescription(aux.Stringid(id,1))
	e2:SetType(EFFECT_TYPE_QUICK_O)
	e2:SetCode(EVENT_FREE_CHAIN)
	e2:SetRange(LOCATION_HAND)
	e2:SetCondition(Kirafan6.spcreamatecon)
	e2:SetCost(Kirafan2.spcost(4))
	e2:SetTarget(Kirafan6.nospcondamtg)
	e2:SetOperation(s.op2)
	c:RegisterEffect(e2)
	local e3=Effect.CreateEffect(c)
	e3:SetDescription(aux.Stringid(10050113,4))
	e3:SetType(EFFECT_TYPE_QUICK_O)
	e3:SetCode(EVENT_FREE_CHAIN)
	e3:SetRange(LOCATION_HAND)
	e3:SetCondition(Kirafan6.spcreamatecon)
	e3:SetCost(Kirafan2.spdotterestcost(1,1,5))
	e3:SetTarget(Kirafan6.nospdamtg)
	e3:SetOperation(Kirafan3.ovallhealop(2))
	c:RegisterEffect(e3)
	local e4=Effect.CreateEffect(c)
	e4:SetDescription(aux.Stringid(10050113,5))
	e4:SetType(EFFECT_TYPE_QUICK_O)
	e4:SetCode(EVENT_FREE_CHAIN)
	e4:SetRange(LOCATION_HAND)
	e4:SetCondition(Kirafan6.spcreamatecon)
	e4:SetCost(Kirafan2.spdotterestcost(1,1,6))
	e4:SetTarget(Kirafan6.nospdamtg)
	e4:SetOperation(s.dotteop2)
	c:RegisterEffect(e4)
	Kirafan3.SpCreamateCharacter(c)
end
function s.op1(e,tp,eg,ep,ev,re,r,rp)
	Kirafan6.firafandotteop(e,tp,eg,ep,ev,re,r,rp,3)
end
function s.op2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
    Kirafan6.kirafandrawop(e,tp,eg,ep,ev,re,r,rp,1)
	Kirafan6.guagetrigger(c)
end
function s.dotteop2(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local g=Duel.GetMatchingGroup(Kirafan6.NoEmFzonefilter,tp,LOCATION_MZONE,0,nil)
	Kirafan6.atkchange(e,tp,eg,ep,ev,re,r,rp,PHASE_END,3,g,1)
end