local s,id=GetID()
function s.initial_effect(c)
	Kirafan5.KnCreamateCharacter(c)
	Kirafan5.Aggroknight(c)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCondition(Kirafan6.spcreamatecon)
	e1:SetCost(Kirafan2.dottecost(1))
	e1:SetTarget(Kirafan3.sghealtg)
	e1:SetOperation(Kirafan3.sghealop(1))
	c:RegisterEffect(e1)
end