local s,id=GetID()
function s.initial_effect(c)
	Kirafan2.CreamateCharacter(c)
	local e1=Effect.CreateEffect(c)
    e1:SetType(EFFECT_TYPE_SINGLE+EFFECT_TYPE_CONTINUOUS)
    e1:SetCode(EVENT_PRE_DAMAGE_CALCULATE)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetCondition(s.battlecon)
	e1:SetOperation(s.battleop)
    c:RegisterEffect(e1)
	local e5=Effect.CreateEffect(c)
	e5:SetDescription(aux.Stringid(10050111,5))
	e5:SetCategory(CATEGORY_COUNTER)
	e5:SetType(EFFECT_TYPE_QUICK_O)
	e5:SetCode(EVENT_FREE_CHAIN)
	e5:SetRange(LOCATION_MZONE)
	e5:SetCondition(Kirafan6.damcon)
	e5:SetCost(Kirafan2.dottecost(2))
	e5:SetTarget(Kirafan6.nodamtg)
	e5:SetOperation(s.damop)
	c:RegisterEffect(e5)
	Kirafan6.NoDotteEffcon(c,2)
end
function s.battlecon(e,tp,eg,ep,ev,re,r,rp)
	return e:GetHandler():GetCounter(0xb04)>0 and Duel.GetAttacker():IsControler(tp)
end
function s.battleop(e,tp,eg,ep,ev,re,r,rp)
	Kirafan6.atkchange(e,tp,eg,ep,ev,re,r,rp,PHASE_END,3,e:GetHandler(),1)
end
function s.damop(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local enemy=Duel.GetMatchingGroup(Kirafan6.NoEmFzonefilter,tp,0,LOCATION_MZONE,nil)
	local dam=1
	Duel.Damage(1-tp,dam,REASON_EFFECT)
	for wg in enemy:Iter() do
	Kirafan6.damageeff(e,tp,eg,ep,ev,re,r,rp,wg,dam) end
	Kirafan6.statuseff(e,tp,eg,ep,ev,re,r,rp,c,0xb04,3)
	Kirafan6.hungerop(e,tp,eg,ep,ev,re,r,rp)
	Kirafan6.atkchange(e,tp,eg,ep,ev,re,r,rp,PHASE_END,3,e:GetHandler(),1)
	local e1=Effect.CreateEffect(c)
	e1:SetType(EFFECT_TYPE_FIELD+EFFECT_TYPE_CONTINUOUS)
	e1:SetCode(EVENT_PHASE+PHASE_BATTLE)
	e1:SetRange(LOCATION_MZONE)
	e1:SetCountLimit(1)
	e1:SetProperty(EFFECT_FLAG_CANNOT_DISABLE)
	e1:SetReset(RESET_EVENT+RESETS_STANDARD)
	e1:SetOperation(s.healtriggerop)
	c:RegisterEffect(e1)
end
function s.healtriggerop(e,tp,eg,ep,ev,re,r,rp)
	Kirafan6.hpaddop(e,tp,eg,ep,ev,re,r,rp,e:GetHandler(),1)
end