local s,id=GetID()
function s.initial_effect(c)
	Kirafan4.ATKUPDotteTrigger(c)
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(id,0))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetProperty(EFFECT_FLAG_CARD_TARGET)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(s.uniquecon)
	e1:SetCost(Kirafan2.spcost(3))
	e1:SetTarget(Kirafan6.damtg)
	e1:SetOperation(s.op)
	c:RegisterEffect(e1)
	Kirafan3.SpCreamateCharacter(c)
end
function s.uniquecon(e,tp,eg,ep,ev,re,r,rp)
	return Kirafan6.spcreamatecon(e,tp,eg,ep,ev,re,r,rp)
	and Duel.GetMatchingGroupCount(Card.IsCode,tp,LOCATION_SZONE,0,nil,10055612)==0
end
function s.op(e,tp,eg,ep,ev,re,r,rp)
	local c=e:GetHandler()
	local tc=Duel.GetFirstTarget()
	Kirafan6.statuseff(e,tp,eg,ep,ev,re,r,rp,tc,0xb02,1)
	Kirafan6.drawtrigger(c)
end