local s,id=GetID()
function s.initial_effect(c)
	Kirafan3.SpCreamateAllHeal(c,2)	
	local e1=Effect.CreateEffect(c)
	e1:SetDescription(aux.Stringid(10050113,4))
	e1:SetType(EFFECT_TYPE_QUICK_O)
	e1:SetCode(EVENT_FREE_CHAIN)
	e1:SetRange(LOCATION_HAND)
	e1:SetCondition(Kirafan6.spcreamatecon)
	e1:SetCost(Kirafan2.spdottecost(1,5))
	e1:SetTarget(Kirafan6.nospcondamtg)
	e1:SetOperation(s.dotteop)
	c:RegisterEffect(e1)
	Kirafan3.SpCreamateCharacter(c)
end
function s.dotteop(e,tp,eg,ep,ev,re,r,rp)
	Kirafan6.kirafandrawop(e,tp,eg,ep,ev,re,r,rp,2)
end